spring:
  profiles:
    active: default,local
  application:
    name: zuul
server:
  use-forward-headers: true
zuul:
  add-host-header: true
  add-proxy-headers: true
  sensitive-headers: Cookie,Set-Cookie
  routes:
    uaa:
      path: /uaa/**
      service-id: oauth-v1
      strip-prefix: false
      sensitive-headers:
    me:
      path: /me/**
      service-id: employees-v1
      strip-prefix: false
    employees:
      path: /employees/**
      service-id: employees-v1
      strip-prefix: false
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
security:
  basic:
    enabled: false
logging:
  level:
    org:
      springframework:
        cloud:
          netflix:
            zuul: TRACE
    com:
      gft:
        zuul: TRACE
      netflix:
        eureka: ERROR
        discovery: ERROR